import { parseScenario, type Scenario, type ScenarioInput } from "../domain/scenario";

/**
 * Original demo scenario. Exercises NPCs, relationships, abilities, inventory,
 * a System, quests, a mutable timeline, locations, secrets and memory.
 */
const input: ScenarioInput = {
  id: "aetherfall-academy",
  version: "1.0.0",
  metadata: {
    title: "Aetherfall Academy",
    shortDescription:
      "Ты просыпаешься в зале прибытия огромной магической академии, а перед глазами вспыхивает голубое окно неизвестной Системы.",
    fullDescription:
      "Академия Этерфолл парит над расколотой долиной, удерживаемая остатками древнего Эфира. Каждый год сюда прибывают одарённые со всего континента. В этом году прибыл ещё и ты — человек из другого мира, которого никто не ждал. Система Эха позволяет тебе запоминать и повторять чужие техники, но за каждой силой следят. До Ночи Пепла осталось две недели, и только ты знаешь, что она наступит.",
    authorName: "Aetherfall Team",
    origin: "original",
    allowRemix: true,
    language: "ru",
  },
  tags: {
    genre: ["Isekai", "Fantasy", "Adventure"],
    setting: ["Magic Academy", "Floating City"],
    tone: ["Adventure", "Mystery"],
    themes: ["Friendship", "Rivalry", "Hidden Conspiracy"],
    features: ["System", "Sandbox", "Canon Knowledge"],
    content: ["Mild Violence"],
  },
  world: {
    name: "Эйрен",
    description:
      "Континент, расколотый Падением Эфира триста лет назад. Магия держится на Эфире — светящейся субстанции, что сочится из разломов. Академия Этерфолл — крупнейшая школа магии, парящая над Долиной Разлома.",
    history:
      "Триста лет назад Эфирная Империя попыталась подчинить источник магии. Источник раскололся — это Падение Эфира. С тех пор магов обучают строго, а запретные ветви магии хранятся в Закрытом Архиве.",
    geography: "Академия парит над Долиной Разлома. Внизу — городок Веспер, связанный с академией подъёмными платформами.",
    technologyLevel: "Позднее средневековье, усиленное артефактами на Эфире.",
    magicSystem:
      "Маг черпает Эфир через внутренний круг (ману). Заклинания требуют формулы, воли и концентрации. Перерасход маны вызывает Эфирный ожог.",
    powerSystem: "Ранги учеников: Искра, Пламя, Звезда. Профессора — Архимаги.",
    politics: "Академией управляет Совет под председательством ректора. Знатные дома давят на Совет, чтобы продвигать своих наследников.",
    economy: "Валюта — серебряные кроны. Ученики получают стипендию и подрабатывают в Веспере.",
    culture: "Ценится талант, но происхождение решает многое. Дуэли между учениками разрешены на тренировочной площадке.",
    religion: "Культ Тихого Пламени почитает Эфир как дыхание мира.",
    importantRules: [
      "Запретная магия (магия душ, копирование чужих техник) карается изгнанием.",
      "Пепельный Круг — тайная организация, которая хочет повторить Падение Эфира.",
      "Никто в мире не знает о существовании других миров.",
    ],
  },
  calendar: {
    monthNames: ["Ледень", "Метелец", "Пробуд", "Капель", "Цветень", "Зной", "Жатва", "Листопад", "Туманник", "Стужень", "Снежень", "Звездень"],
    daysPerMonth: 30,
    hoursPerDay: 24,
    yearLabel: "Год",
  },
  mechanics: {
    stats: [
      { id: "health", name: "Здоровье", kind: "resource", min: 0, max: 100, default: 100 },
      { id: "energy", name: "Мана", kind: "resource", min: 0, max: 100, default: 60 },
      { id: "strength", name: "Сила", kind: "attribute", min: 1, max: 30, default: 8 },
      { id: "intellect", name: "Интеллект", kind: "attribute", min: 1, max: 30, default: 12 },
      { id: "will", name: "Воля", kind: "attribute", min: 1, max: 30, default: 10 },
      { id: "charm", name: "Обаяние", kind: "attribute", min: 1, max: 30, default: 10 },
    ],
    healthResourceId: "health",
    energyResourceId: "energy",
    equipmentSlots: ["weapon", "body", "accessory"],
  },
  locations: [
    {
      id: "hall-of-arrival",
      name: "Зал Прибытия",
      description: "Высокий зал из белого камня с витражами, изображающими Падение Эфира. Здесь новички получают распределение.",
      region: "Академия",
      connections: [{ locationId: "courtyard", travelMinutes: 5 }],
      visualDescription: "white marble hall, tall stained glass windows, floating blue motes of light",
    },
    {
      id: "courtyard",
      name: "Парящий двор",
      description: "Сад на краю парящей платформы. Отсюда видна Долина Разлома и подъёмные платформы в Веспер.",
      region: "Академия",
      connections: [
        { locationId: "hall-of-arrival", travelMinutes: 5 },
        { locationId: "dormitory", travelMinutes: 10 },
        { locationId: "library", travelMinutes: 10 },
        { locationId: "training-grounds", travelMinutes: 15 },
        { locationId: "headmaster-tower", travelMinutes: 20 },
        { locationId: "vesper", travelMinutes: 45 },
      ],
    },
    {
      id: "dormitory",
      name: "Общежитие «Искра»",
      description: "Старое крыло для новичков. Скрипучие лестницы, общая гостиная с камином.",
      region: "Академия",
      connections: [{ locationId: "courtyard", travelMinutes: 10 }],
    },
    {
      id: "library",
      name: "Библиотека Шёпотов",
      description: "Бесконечные стеллажи, парящие лампы. По ночам из глубины доносится шёпот.",
      region: "Академия",
      connections: [
        { locationId: "courtyard", travelMinutes: 10 },
        { locationId: "sealed-archive", travelMinutes: 15 },
      ],
    },
    {
      id: "sealed-archive",
      name: "Закрытый Архив",
      description: "Подземное хранилище запретных знаний за латунной дверью с семью замками.",
      region: "Академия",
      hidden: true,
      connections: [{ locationId: "library", travelMinutes: 15 }],
    },
    {
      id: "training-grounds",
      name: "Тренировочная арена",
      description: "Круглая арена с защитными рунами. Здесь проходят дуэли и вступительное испытание.",
      region: "Академия",
      connections: [{ locationId: "courtyard", travelMinutes: 15 }],
    },
    {
      id: "headmaster-tower",
      name: "Башня ректора",
      description: "Самая высокая башня академии. Вход только по приглашению.",
      region: "Академия",
      connections: [{ locationId: "courtyard", travelMinutes: 20 }],
    },
    {
      id: "vesper",
      name: "Веспер",
      description: "Шумный городок у подножия академии: рынок артефактов, таверна «Падший Фонарь», доки платформ.",
      region: "Долина Разлома",
      connections: [{ locationId: "courtyard", travelMinutes: 45 }],
    },
  ],
  npcs: [
    {
      id: "lira",
      name: "Лира Венн",
      description: "Первокурсница, огненный маг из обедневшего рода. Соседка героя по распределению.",
      appearance: "Рыжие волосы, собранные в небрежный хвост, янтарные глаза, на запястье — ожоговый шрам.",
      personality: "Прямолинейная, гордая, наблюдательная. Не терпит лжи, но легко смеётся.",
      speechStyle: "Говорит быстро и резко, часто подкалывает, называет героя «новенький».",
      goals: ["Доказать, что её род чего-то стоит", "Пройти вступительное испытание лучшей"],
      fears: ["Потерять контроль над огнём, как в детстве"],
      secrets: [{ id: "lira-burn", description: "Шрам Лиры — след случая, когда она случайно сожгла дом семьи.", importance: 60 }],
      abilityIds: ["mana-bolt"],
      startingLocationId: "hall-of-arrival",
      knowledge: ["Вступительное испытание пройдёт на третий день на арене.", "Профессор Морн ведёт практическую магию."],
      startingMood: "настороженность",
      startingRelationship: { trust: 0, friendship: 5, suspicion: 20 },
      aiInstructions: "Лира не доверяет тем, кто уходит от ответов. Её симпатию нужно заслужить делом, а не словами.",
      visualProfile: { hair: "messy red ponytail", eyes: "amber", clothing: "academy uniform with rolled sleeves", distinctiveFeatures: "burn scar on left wrist" },
    },
    {
      id: "aldric",
      name: "Профессор Алдрик Морн",
      description: "Преподаватель практической магии. Добродушный на вид, но внимательный до жути.",
      appearance: "Седеющие волосы, аккуратная бородка, очки в тонкой оправе, серый плащ архимага.",
      personality: "Вежливый, терпеливый, любознательный. Никогда не повышает голос.",
      speechStyle: "Говорит мягко, задаёт вопросы вместо утверждений.",
      goals: ["Найти учеников с необычным даром", "Тайно: открыть Закрытый Архив для Пепельного Круга"],
      fears: ["Разоблачение"],
      secrets: [{ id: "aldric-ashen", description: "Морн — агент Пепельного Круга.", importance: 90 }],
      abilityIds: ["arcane-shield", "mana-bolt"],
      factionIds: ["council", "ashen-circle"],
      startingLocationId: "hall-of-arrival",
      knowledge: ["В этом году Эфир в Зале Прибытия вёл себя странно при появлении одного из новичков."],
      startingMood: "любопытство",
      startingRelationship: { trust: 10, respect: 5, suspicion: 15 },
      aiInstructions: "Морн никогда не раскрывает свою принадлежность к Пепельному Кругу без веских доказательств. Он вербует, а не угрожает.",
      visualProfile: { hair: "greying short hair", face: "neat beard, thin-rimmed glasses", clothing: "grey archmage cloak" },
    },
    {
      id: "kael",
      name: "Каэль Дравен",
      description: "Наследник знатного дома Дравен, лучший ученик потока по мнению всех, включая его самого.",
      appearance: "Платиновые волосы, холодные серые глаза, безупречная форма с гербом дома.",
      personality: "Высокомерный, но честный в дуэлях. Уважает силу.",
      speechStyle: "Растягивает слова, говорит снисходительно, никогда не называет по имени, пока не начнёт уважать.",
      goals: ["Стать лучшим учеником академии", "Не опозорить дом"],
      fears: ["Разочаровать отца"],
      abilityIds: ["arcane-shield"],
      factionIds: ["house-draven"],
      startingLocationId: "courtyard",
      startingMood: "скука",
      startingRelationship: { respect: -10, hostility: 10 },
      aiInstructions: "Каэль — соперник, не злодей. Его отношение меняется, если герой побеждает его честно.",
    },
    {
      id: "sefa",
      name: "Архивариус Сефа",
      description: "Хранительница Библиотеки Шёпотов. Возраст неизвестен.",
      appearance: "Маленькая женщина в тёмно-синей мантии, глаза затянуты молочной дымкой, но она видит больше остальных.",
      personality: "Загадочная, ироничная, любит чай и вопросы без ответов.",
      speechStyle: "Отвечает притчами, никогда не говорит прямо.",
      goals: ["Не допустить открытия Закрытого Архива"],
      fears: ["Повторение Падения"],
      startingLocationId: "library",
      knowledge: ["Шёпот из глубины библиотеки усилился в этом месяце.", "Ключи от Архива хранятся у ректора."],
      startingMood: "задумчивость",
      importance: "major",
    },
    {
      id: "ysolde",
      name: "Ректор Изольда Аргент",
      description: "Глава академии и Совета.",
      appearance: "Высокая женщина с белоснежными волосами и посохом из живого дерева.",
      personality: "Холодная, справедливая, прагматичная.",
      speechStyle: "Коротко, по делу.",
      goals: ["Сохранить академию"],
      startingLocationId: "headmaster-tower",
      factionIds: ["council"],
      startingMood: "озабоченность",
      importance: "minor",
    },
  ],
  factions: [
    { id: "council", name: "Совет Академии", description: "Управляет академией.", leaderId: "ysolde", memberIds: ["ysolde", "aldric"], goals: ["Порядок и безопасность"], territory: "Академия" },
    {
      id: "ashen-circle",
      name: "Пепельный Круг",
      description: "Тайная организация, желающая повторить Падение Эфира и переписать мир.",
      leaderId: "aldric",
      memberIds: ["aldric"],
      goals: ["Открыть Закрытый Архив", "Провести ритуал в Ночь Пепла"],
      enemyIds: ["council"],
      startingReputation: 0,
    },
    { id: "house-draven", name: "Дом Дравен", description: "Знатный род, поставляющий магов Совету.", memberIds: ["kael"], goals: ["Влияние в Совете"], allyIds: ["council"] },
  ],
  abilities: [
    { id: "mana-bolt", name: "Стрела маны", description: "Сгусток чистого Эфира, бьющий в цель.", category: "attack", subcategory: "Базовая магия", difficulty: 2, mastery: 20, energyCost: 10, cooldown: 0, tags: ["магия", "дальний бой"] },
    { id: "arcane-shield", name: "Эфирный щит", description: "Полупрозрачный барьер, отражающий удары и заклинания.", category: "defense", subcategory: "Базовая магия", difficulty: 3, mastery: 10, energyCost: 15, cooldown: 10, tags: ["магия", "барьер"] },
    { id: "minor-heal", name: "Малое исцеление", description: "Затягивает неглубокие раны.", category: "healing", subcategory: "Целительство", difficulty: 3, mastery: 10, energyCost: 12, cooldown: 30, effects: [{ type: "resource", resourceId: "health", amount: 20 }], tags: ["магия", "лечение"] },
    { id: "flicker-step", name: "Мерцающий шаг", description: "Мгновенный рывок на несколько метров.", category: "movement", subcategory: "Пространственная магия", difficulty: 5, mastery: 0, energyCost: 20, cooldown: 60, requirements: { minLevel: 3 }, tags: ["магия", "перемещение"] },
    { id: "analyze", name: "Анализ", description: "Системная способность: показывает краткие сведения о человеке, предмете или заклинании.", category: "special", subcategory: "Система Эха", difficulty: 1, mastery: 30, energyCost: 0, cooldown: 5, tags: ["система"] },
    { id: "echo-copy", name: "Эхо", description: "Запоминает технику, которую герой видел вблизи, и позволяет повторить её ослабленную версию. Запретная магия по законам академии.", category: "forbidden", subcategory: "Система Эха", difficulty: 6, mastery: 5, energyCost: 25, cooldown: 120, tags: ["система", "запретное", "копирование"] },
    { id: "whisper-sense", name: "Слух Шёпота", description: "Пассивно: герой слышит голоса Эфира там, где другие слышат тишину.", category: "passive", subcategory: "Врождённое", difficulty: 1, mastery: 0, energyCost: 0, passive: true, hidden: true, tags: ["эфир"] },
  ],
  items: [
    { id: "academy-uniform", name: "Форма академии", description: "Тёмно-синяя форма первокурсника с серебряной нашивкой.", type: "equipment", slot: "body", stackable: false, value: 5 },
    { id: "novice-wand", name: "Палочка новичка", description: "Ясеневая палочка, облегчающая концентрацию.", type: "equipment", slot: "weapon", stackable: false, value: 10, effects: [{ type: "stat", statId: "intellect", amount: 1 }] },
    { id: "mana-potion", name: "Зелье маны", description: "Синее зелье, восстанавливающее 30 маны.", type: "consumable", value: 15, effects: [{ type: "resource", resourceId: "energy", amount: 30 }] },
    { id: "healing-salve", name: "Целебная мазь", description: "Восстанавливает 25 здоровья.", type: "consumable", value: 12, effects: [{ type: "resource", resourceId: "health", amount: 25 }] },
    { id: "brass-key", name: "Латунный ключ", description: "Тяжёлый ключ с семью зубцами. Один из ключей от Закрытого Архива.", type: "key", stackable: false, value: 0 },
    { id: "admission-letter", name: "Письмо о зачислении", description: "Письмо с твоим именем. Ты не помнишь, чтобы подавал заявку.", type: "misc", stackable: false },
    { id: "focus-tea", name: "Чай сосредоточения", description: "Даёт эффект «Ясный ум» на 2 часа.", type: "consumable", value: 8, effects: [{ type: "status", name: "Ясный ум", description: "+концентрация при изучении магии", durationMinutes: 120 }] },
  ],
  lore: [
    { id: "aether", type: "magic", name: "Эфир", description: "Светящаяся субстанция, источник всей магии Эйрена. Сочится из разломов.", tags: ["магия"] },
    { id: "the-fall", type: "historical_event", name: "Падение Эфира", description: "Катастрофа трёхсотлетней давности, расколовшая источник магии и континент.", tags: ["история"] },
    { id: "ashen-circle-lore", type: "faction", name: "Пепельный Круг", description: "Слухи о тайном обществе, поклоняющемся Падению. Большинство считает их сказкой.", visibility: "hidden", tags: ["заговор"], relatedIds: ["the-fall"] },
    { id: "night-of-ash", type: "historical_event", name: "Ночь Пепла", description: "Ритуал Пепельного Круга, который должен расколоть второй источник Эфира под академией.", visibility: "secret", aiInstructions: "Раскрывать только при серьёзных находках героя.", tags: ["заговор"] },
    { id: "echo-phenomenon", type: "concept", name: "Феномен Эха", description: "Древние тексты упоминают «Эхо» — способность повторять чужую магию. Считается запретной.", visibility: "hidden", tags: ["запретное"] },
  ],
  quests: [
    {
      id: "entrance-trial",
      title: "Вступительное испытание",
      description: "Пройди вступительное испытание на арене, чтобы остаться в академии.",
      objectives: [
        { id: "attend-ceremony", description: "Посетить церемонию распределения" },
        { id: "prepare", description: "Подготовиться к испытанию", optional: true },
        { id: "pass-trial", description: "Пройти испытание на арене" },
      ],
      giverNpcId: "aldric",
      rewards: { xp: 150, items: [{ itemId: "mana-potion", quantity: 2 }], currency: { crowns: 50 } },
    },
    {
      id: "whispers-library",
      title: "Шёпот в библиотеке",
      description: "Что-то зовёт из глубины Библиотеки Шёпотов.",
      objectives: [
        { id: "find-source", description: "Найти источник шёпота" },
        { id: "find-key", description: "Найти ключ от Закрытого Архива" },
        { id: "decide-archive", description: "Решить судьбу Закрытого Архива" },
      ],
      hidden: true,
      rewards: { xp: 300 },
    },
    {
      id: "lira-trust",
      title: "Огонь под контролем",
      description: "Лира боится своей силы. Возможно, ей нужна помощь.",
      objectives: [{ id: "learn-fear", description: "Узнать, чего боится Лира" }, { id: "help-train", description: "Помочь ей тренироваться" }],
      giverNpcId: "lira",
      rewards: { xp: 100 },
      hidden: true,
    },
  ],
  timeline: [
    { id: "sorting-ceremony", title: "Церемония распределения", date: { year: 1247, month: 1, day: 1, hour: 18 }, participants: ["ysolde", "aldric", "lira", "kael"], locationId: "hall-of-arrival", description: "Новички получают распределение по общежитиям.", importance: 50, mutable: false, outcome: "Новичков распределили по общежитиям. Лира и герой попали в «Искру»." },
    { id: "entrance-trial-event", title: "Вступительное испытание", date: { year: 1247, month: 1, day: 3, hour: 10 }, participants: ["aldric", "lira", "kael"], locationId: "training-grounds", description: "Публичное испытание новичков на арене.", importance: 60, mutable: true, outcome: "Испытание прошло. Каэль Дравен показал лучший результат." },
    {
      id: "library-incident",
      title: "Инцидент в библиотеке",
      date: { year: 1247, month: 1, day: 7, hour: 23 },
      conditions: [{ type: "flag", key: "archive_secured", equals: false }],
      participants: ["aldric", "sefa"],
      locationId: "library",
      description: "Кто-то пытается взломать Закрытый Архив. Архивариус Сефа ранена.",
      importance: 75,
      mutable: true,
      hidden: true,
      effects: [{ type: "flag", key: "sefa_injured", value: true }],
      outcome: "Ночью кто-то пытался взломать Закрытый Архив. Архивариус Сефа ранена и лежит в лазарете.",
    },
    {
      id: "night-of-ash-event",
      title: "Ночь Пепла",
      date: { year: 1247, month: 1, day: 14, hour: 0 },
      conditions: [
        { type: "flag", key: "ashen_exposed", equals: false },
        { type: "npc_alive", npcId: "aldric", alive: true },
      ],
      participants: ["aldric"],
      locationId: "sealed-archive",
      description: "Пепельный Круг проводит ритуал под академией.",
      importance: 95,
      mutable: true,
      hidden: true,
      outcome: "Ночь Пепла: под академией вспыхнул ритуальный круг, платформа содрогнулась, часть Эфира погасла.",
    },
  ],
  system: {
    enabled: true,
    name: "Система Эха",
    description: "Голубые полупрозрачные окна, которые видит только герой. Система выдаёт задания, начисляет опыт и позволяет копировать увиденные техники.",
    voice: "Сухие уведомления в квадратных скобках, иногда с неуместной иронией. Пример: [Задание обновлено. Постарайтесь не умереть.]",
    modules: { levels: true, experience: true, skillPoints: true, attributePoints: true, quests: true, achievements: true, shop: false, titles: true, classes: false, perks: false, dailyQuests: false },
    xpCurve: { base: 100, growth: 1.5 },
    skillPointsPerLevel: 1,
    attributePointsPerLevel: 2,
    currencies: [{ id: "crowns", name: "Серебряные кроны" }],
    achievements: [
      { id: "first-echo", name: "Первое Эхо", description: "Впервые скопировать чужую технику." },
      { id: "trial-passed", name: "Принят", description: "Пройти вступительное испытание." },
    ],
    titles: [{ id: "otherworlder", name: "Гость из-за грани", description: "Скрытый титул." }],
  },
  characterCreation: {
    fields: [
      { id: "name", label: "Имя", type: "text", required: true, placeholder: "Как тебя зовут?" },
      { id: "gender", label: "Пол", type: "text" },
      { id: "age", label: "Возраст", type: "number", placeholder: "17" },
      { id: "appearance", label: "Внешность", type: "textarea" },
      { id: "personality", label: "Характер", type: "textarea" },
      { id: "background", label: "Кем ты был в прошлом мире", type: "textarea", placeholder: "Студент, программист, повар..." },
      {
        id: "affinity",
        label: "Склонность к магии",
        type: "select",
        required: true,
        options: [
          { value: "arcane", label: "Чистый Эфир", description: "Стабильная мана и защита.", grants: { abilityIds: ["arcane-shield"], stats: { will: 2 } } },
          { value: "life", label: "Жизнь", description: "Целительство и выносливость.", grants: { abilityIds: ["minor-heal"], items: [{ itemId: "healing-salve", quantity: 1 }] } },
          { value: "motion", label: "Движение", description: "Ловкость и скорость.", grants: { stats: { strength: 2 }, items: [{ itemId: "focus-tea", quantity: 1 }] } },
        ],
      },
    ],
    startingAbilityIds: ["mana-bolt", "analyze", "echo-copy", "whisper-sense"],
    startingItems: [
      { itemId: "academy-uniform", quantity: 1 },
      { itemId: "novice-wand", quantity: 1 },
      { itemId: "mana-potion", quantity: 1 },
      { itemId: "admission-letter", quantity: 1 },
    ],
    attributePoints: 3,
  },
  start: {
    date: { year: 1247, month: 1, day: 1, hour: 14, minute: 0 },
    locationId: "hall-of-arrival",
    situation:
      "Герой очнулся на холодном полу Зала Прибытия среди других новичков, в чужой форме и с письмом о зачислении в кармане. Перед глазами висит голубое окно: [Система Эха активирована].",
    playerBackground: "Обычный человек из современного мира, погибший и очнувшийся здесь.",
    playerKnowledge: "partial",
    knownFacts: [
      "Герой смутно помнит, что этот мир похож на сюжет новеллы, которую он читал: в ней на 14-й день случилась «Ночь Пепла».",
      "В новелле профессор Морн казался добрым наставником, но подробностей герой не помнит.",
    ],
    playerSecrets: [
      { id: "otherworlder", description: "Герой — попаданец из другого мира.", keywords: ["другого мира", "другой мир", "иного мира", "попаданец", "переселенец"], importance: 95 },
      { id: "echo-system", description: "Герой видит Систему Эха и может копировать чужие техники.", keywords: ["Система Эха", "копируешь чужие", "твоя система"], importance: 85 },
    ],
    currency: { crowns: 20 },
    activeQuestIds: ["entrance-trial"],
    flags: { archive_secured: false, ashen_exposed: false },
    openingScene:
      "Камень под щекой холодный. Где-то высоко звенят витражи, и сквозь веки пробивается голубой свет — не солнечный, слишком ровный. Ты открываешь глаза и видишь перед собой полупрозрачное окно с аккуратными буквами:\n\n[Система Эха активирована. Добро пожаловать, Гость.]\n\nВокруг шумят десятки молодых голосов. Кто-то в двух шагах фыркает: рыжая девушка в такой же синей форме смотрит на тебя сверху вниз.\n\n— Ты так и собираешься лежать, новенький? Церемония через четыре часа, а профессор Морн уже второй раз смотрит в нашу сторону.",
  },
  rules: {
    tone: "Приключение с нотками тайны и лёгкого юмора",
    narrativeStyle: "Живая проза ранобэ: атмосферные описания, диалоги, внутренние ощущения героя",
    responseLength: "medium",
    pov: "second",
    violence: "medium",
    romance: "low",
    comedy: "medium",
    difficulty: "normal",
    canonStrictness: "loose",
    playerFreedom: "sandbox",
    npcAutonomy: "high",
    worldLethality: "medium",
    playerCanDie: false,
    progressionSpeed: "normal",
    worldReactivity: "living",
    customInstructions: "Системные уведомления оформляй в квадратных скобках отдельной строкой.",
  },
  storyHooks: [
    "Кто прислал герою письмо о зачислении?",
    "Почему Эфир реагирует на героя?",
    "Что шепчет из глубины библиотеки?",
    "Сможет ли герой предотвратить Ночь Пепла?",
  ],
};

export function createAetherfallAcademy(): Scenario {
  return parseScenario(structuredClone(input));
}
